# Generated by Django 5.0 on 2023-12-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatsBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsmodel',
            name='GroupName',
            field=models.TextField(default=None),
        ),
    ]
